<?php
$HOSTNAME='your_hostname';
$USERNAME='your_username';
$PASSWORD='your_password';
$DATABaSE='your_databasename';
$con=mysqli_connect($HOSTNAME,$USERNAME,$PASSWORD,$DATABaSE);
if(!$con){
    die(mysqli_error($con)); 
} 
?>
